### ISSUE TITLE
Team Fortress 2 over telnet possible?

### ISSUE THREAD

**Issue by godrider** [403-Fruit/csctl#2]
Is TF2, or any Source game, over telnet possible like with CS:GO shown here? I tried the script for TF2 but couldn't get it to work. Does -netconport even exist in TF2? The script itself looks very useful!

**Comment by 403-Fruit** [comment]
It looks like TF2 doesn't have the `-netconport` launch option. TF2 doesn't listen on any ports and the string "netconport" doesn't seem to appear in any of the binaries. Sorry!
