### ISSUE TITLE
Can't set it up

### ISSUE THREAD

**Issue by FFGamer04** [403-Fruit/csctl#3]
When I run the "Set up commands in python, this happens
![D__Python_python exe 22_03_2021 10_23_17](https://user-images.githubusercontent.com/81158749/111975658-c06fb180-8af8-11eb-9e67-197dc5a8e6d6.png)

**Comment by deepakrvg** [comment]
You are using python shell. Try using terminal or command prompt in windows

**Comment by FFGamer04** [comment]
It didn't work either. Can you give me a short tutorial? I'm totally new to python

**Comment by deepakrvg** [comment]
First install git from browser. Run it.
Then use command prompt or git bash.
Then use command git clone ...

Run pip install ... on command prompt or terminal

**Comment by deepakrvg** [comment]
> It didn't work either. Can you give me a short tutorial? I'm totally new to python

> pip install psutil
Try using these command on your terminal

**Comment by FFGamer04** [comment]
So: I ran the first command on git, then the second on command prompt, but, when I tried the 3rd, this happened: 
"'pip' is not recognized as an internal or external command,
operable program or batch file."

**Comment by deepakrvg** [comment]
Open command prompt in administrative mode and run python -m pip install psutil

**Comment by FFGamer04** [comment]
"Python not found" I'm terribly sorry to be bothering you, but I really want to run this

**Comment by deepakrvg** [comment]
Install python from python.org

**Comment by FFGamer04** [comment]
It is installed and running

**Comment by deepakrvg** [comment]
![psutil python](https://user-images.githubusercontent.com/76244467/111983516-38a59980-8b30-11eb-8a59-d49be8adc435.JPG)

check command should be same means lower case as typed

**Comment by FFGamer04** [comment]
![Captura de ecrã 2021-03-22 113325](https://user-images.githubusercontent.com/81158749/111983825-7986b980-8b02-11eb-8854-83d65d3bffd8.png)
The error message is in portuguese, but the translation is "Python not found, execute without arguments to install from microsoft store or deactivate this shortcut in Settings > manage aplication execution aliases"

**Comment by deepakrvg** [comment]
Reinstall python and install python from python.org
While executing python make sure "add python to path" option is checked

**Comment by FFGamer04** [comment]
Done, it was the add python to path option, thanks!

**Comment by FFGamer04** [comment]
How do I run it now?

**Comment by deepakrvg** [comment]
After installing psutil from pip use it in your program by importing that module.
import psutil

**Comment by FFGamer04** [comment]
on python?

**Comment by deepakrvg** [comment]
Yes

**Comment by FFGamer04** [comment]
![image](https://user-images.githubusercontent.com/81158749/111986413-d20b8600-8b05-11eb-9621-cef7fc6e8572.png)
What am I meant  to do?

**Comment by deepakrvg** [comment]
Write your program. Or see tutorials for using that module.

**Comment by FFGamer04** [comment]
Can I write the program in Notepad++ and then add it to the "examples folder"?

**Comment by deepakrvg** [comment]
Yes you can write program in any text editor like notepad or notepad++.
Just save the file with .py extension

**Comment by FFGamer04** [comment]
ok thanks! Do i need to have python running in backgound while playing?

**Comment by deepakrvg** [comment]
Yes you have to interpret that program by running python in background

**Comment by FFGamer04** [comment]
ok thx

**Comment by FFGamer04** [comment]
When typing in the console, should I add the suffix .py?
