### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by FFGamer04** [403-Fruit/csctl#4]
When I launch CS (with the -netconport 2121 launch option), this error message appears
![Linha de comandos 23_03_2021 12_20_39](https://user-images.githubusercontent.com/81158749/112145507-5e837a80-8bd2-11eb-8880-5fb0046728af.png)

**Comment by FFGamer04** [comment]
Managed to fix it: run through python instead of command prompt

**Comment by 403-Fruit** [comment]
Nice! Just a tip, it looks a lot prettier if you use [Windows Terminal](https://github.com/microsoft/terminal) rather than command prompt. Command prompt can't display colors in the same way.
